import b5 from "../images/b5.jpg";
import b6 from "../images/b6.jpg";
import b7 from "../images/b7.jpg";
import b8 from "../images/b8.jpg";

export default {
  items: [
    {
      id:"1",
      title: "Ikigai",
      mainTitle:
        "Ikigai - The Japanese Secret to a Long and Happy Life(English, Hardcover, Garcia Hector)",
      category: "books",
      price: 249,
      ratings: 4.5,
      author: "Hector Garcia",
      popularity: 81,
      image: b5,
      link: "/",
    },
    {
      id: "2",
      title: "The Power of Subconscious",
      mainTitle:
        "The Power of your Subconscious Mind  (English, Paperback, Dr. Murphy Joseph)",
      category: "books",
      price: 149,
      ratings: 5,
      author: "Joseph Murphy",
      popularity: 91,
      image: b6,
      link: "/",
    },
    {
      id: "3",
      title: "Think and Grow Rich",
      mainTitle:
        "Think and Grow Rich and the Law of Success in Sixteen Lessons  (English, Paperback, Hill Napoleon)",
      category: "books",
      price: 150,
      ratings: 5,
      author: "Napolean Hill",
      popularity: 92,
      image: b7,
      link: "/",
    },
    {
      id: "4",
      title: "How to stop worrying and start living",
      mainTitle:
        "How To Stop Worrying And Start Living  (English, Dale Carnegie)",
      category: "books",
      price: 199,
      ratings: 4.5,
      author: "Dale carnigie",
      popularity: 87,
      image: b8,
      link: "/",
    },
    // repeat
    {
      id: "5",
      title: "Ikigai",
      mainTitle:
        "Ikigai - The Japanese Secret to a Long and Happy Life(English, Hardcover, Garcia Hector)",
      category: "books",
      price: 249,
      ratings: 4.5,
      author: "Hector Garcia",
      popularity: 81,
      image: b5,
      link: "/",
    },
    {
      id: "6",
      title: "The Power of Subconscious",
      mainTitle:
        "The Power of your Subconscious Mind  (English, Paperback, Dr. Murphy Joseph)",
      category: "books",
      price: 149,
      ratings: 5,
      author: "Joseph Murphy",
      popularity: 91,
      image: b6,
      link: "/",
    },
    {
      id: "7",
      title: "Think and Grow Rich",
      mainTitle:
        "Think and Grow Rich and the Law of Success in Sixteen Lessons  (English, Paperback, Hill Napoleon)",
      category: "books",
      price: 150,
      ratings: 5,
      author: "Napolean Hill",
      popularity: 92,
      image: b7,
      link: "/",
    },
    {
      id: "8",
      title: "How to stop worrying and start living",
      mainTitle:
        "How To Stop Worrying And Start Living  (English, Dale Carnegie)",
      category: "books",
      price: 199,
      ratings: 4.5,
      author: "Dale carnigie",
      popularity: 87,
      image: b8,
      link: "/",
    },
    {
      id: "9",
      title: "Ikigai",
      mainTitle:
        "Ikigai - The Japanese Secret to a Long and Happy Life(English, Hardcover, Garcia Hector)",
      category: "books",
      price: 249,
      ratings: 4.5,
      author: "Hector Garcia",
      popularity: 81,
      image: b5,
      link: "/",
    },
    {
      id: "10",
      title: "The Power of Subconscious",
      mainTitle:
        "The Power of your Subconscious Mind  (English, Paperback, Dr. Murphy Joseph)",
      category: "books",
      price: 149,
      ratings: 5,
      author: "Joseph Murphy",
      popularity: 91,
      image: b6,
      link: "/",
    },
    {
      id: "11",
      title: "Think and Grow Rich",
      mainTitle:
        "Think and Grow Rich and the Law of Success in Sixteen Lessons  (English, Paperback, Hill Napoleon)",
      category: "books",
      price: 150,
      ratings: 5,
      author: "Napolean Hill",
      popularity: 92,
      image: b7,
      link: "/",
    },
    {
      id: "12",
      title: "How to stop worrying and start living",
      mainTitle:
        "How To Stop Worrying And Start Living  (English, Dale Carnegie)",
      category: "books",
      price: 199,
      ratings: 4.5,
      author: "Dale carnigie",
      popularity: 87,
      image: b8,
      link: "/",
    },
    {
      id: "13",
      title: "Ikigai",
      mainTitle:
        "Ikigai - The Japanese Secret to a Long and Happy Life(English, Hardcover, Garcia Hector)",
      category: "books",
      price: 249,
      ratings: 4.5,
      author: "Hector Garcia",
      popularity: 81,
      image: b5,
      link: "/",
    },
    {
      id: "14",
      title: "The Power of Subconscious",
      mainTitle:
        "The Power of your Subconscious Mind  (English, Paperback, Dr. Murphy Joseph)",
      category: "books",
      price: 149,
      ratings: 5,
      author: "Joseph Murphy",
      popularity: 91,
      image: b6,
      link: "/",
    },
    {
      id: "15",
      title: "Think and Grow Rich",
      mainTitle:
        "Think and Grow Rich and the Law of Success in Sixteen Lessons  (English, Paperback, Hill Napoleon)",
      category: "books",
      price: 150,
      ratings: 5,
      author: "Napolean Hill",
      popularity: 92,
      image: b7,
      link: "/",
    },
    {
      id: "16",
      title: "How to stop worrying and start living",
      mainTitle:
        "How To Stop Worrying And Start Living  (English, Dale Carnegie)",
      category: "books",
      price: 199,
      ratings: 4.5,
      author: "Dale carnigie",
      popularity: 87,
      image: b8,
      link: "/",
    },
  ],
};
