import wd1 from "../images/wd1.jpg";
import wd2 from "../images/wd2.jpg";
import wd3 from "../images/wd3.jpg";
import wd4 from "../images/wd4.jpg";
import wd5 from "../images/wd5.jpg";
import wd6 from "../images/wd6.jpg";
import wd7 from "../images/wd7.jpg";
import wd8 from "../images/wd8.jpg";
import wd9 from "../images/wd9.jpg";
import wd10 from "../images/wd10.jpg";
import wd11 from "../images/wd11.jpg";

export default {
  items: [
    {
      id: "1",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd1,
      link: "/",
    },
    {
      id: "2",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd2,
      link: "/",
    },
    {
      id: "3",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd3,
      link: "/",
    },
    {
      id: "4",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd4,
      link: "/",
    },
    {
      id: "5",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd5,
      link: "/",
    },
    {
      id: "6",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd6,
      link: "/",
    },
    {
      id: "7",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd7,
      link: "/",
    },
    {
      id: "8",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd8,
      link: "/",
    },
    {
      id: "9",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd9,
      link: "/",
    },
    {
      id: "10",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd10,
      link: "/",
    },
    {
      id: "11",
      title: "Women Dress yellow",
      mainTitle: "Beautiful dress for Party",
      category: "womenDress",
      price: 1999,
      ratings: 4.5,
      popularity: 81,
      image: wd11,
      link: "/",
    },
  ],
};
